name: automanager
description: .
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.12.9+5
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.5.1
  flutter_easyloading: ^1.0.1
  flutter_spinkit: ^4.1.2+1
  connectivity: ^0.4.8+6

flutter:
  uses-material-design: true


  assets:
    - assets/images/image_pushing_cart.png
    - assets/images/image_investment_register.png
    - assets/images/image_investing_stocks.png

    - assets/images/image_add_stock.png
    - assets/images/image_make_sale.png
    - assets/images/image_update_stock.png
    - assets/images/image_view_sales.png
    - assets/images/image_view_storage.png
    - assets/images/image_view_roles.png
    - assets/images/image_add_image.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
